# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    administration.user:
        class: AdminBundle\Admin\UserAdmin
        arguments: [~, UserBundle\Entity\User, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'Data Management', label: 'User' }

    trenkwalder.user_provider:
        class: TrenkwalderBundle\Security\User\UserProvider
        arguments: ['@doctrine.orm.entity_manager']
